#! /bin/sh
# /etc/init.d/zapfclient

### BEGIN INIT INFO
# Provides:     zapfclient
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Description: starts the ZapfClient
### END INIT INFO

case "$1" in
	start)
		echo "Starting ZapfClient"
		cd /home/pi/client/zapfmaster2000-zapfkit-client
		sudo ./zapfmaster2000-zapfkit-client&
		;;
	stop)
		echo "Stopping ZapfClient"
		echo "0=0" > /dev/pi-blaster
		echo "1=0" > /dev/pi-blaster
		echo "4=0" > /dev/pi-blaster
		zapfpid=$(pidof zapfmaster2000-zapfkit-client)
		sudo kill -s SIGINT $zapfpid
		;;
	*)
		echo "Usage: /etc/init.d/zapfclient {start|stop}"
		exit 1
		;;
esac

exit 0
