/**
 * position:[row,column] 
 */
ZMO.modules_properties ={
		front:{
			sections:{
				navigation:[{
					moduleId:"receiveChallenge",
					ratio:"100%",
					position:[0,0],
					params:{}
				},{
					moduleId:"header",
					ratio:"100%",
					position:[0,0],
				}],
				main:[{
					moduleId:"drawfeed",
					ratio:"100%",
					position:[0,0],
					params:{isMobile:true}
				}],
				  
				footer:[],
				side:[{
					moduleId:"sideNavigation",
					ratio:"100%",
					position:[0,0]
				},{
					moduleId:"challengeUserList",
					ratio:"100%",
					position:[0,0]
				}]
			}
		},
		challenges:{
			sections:{
				navigation:[{
					moduleId:"receiveChallenge",
					ratio:"100%",
					position:[0,0]
				},{
					moduleId:"header",
					ratio:"100%",
					position:[0,0],
				}],
				main:[{
					moduleId:"challenges",
					ratio:"100%",
					position:[0,0],
					params:{
						isMobile:true
					}
				}],
				  
				footer:[],
				side:[{
					moduleId:"sideNavigation",
					ratio:"100%",
					position:[0,0]
				},{
					moduleId:"challengeUserList",
					ratio:"100%",
					position:[0,0]
				}]
			}
		},
		
		stats:{
			sections:{
				navigation:[{
					moduleId:"receiveChallenge",
					ratio:"100%",
					position:[0,0]
				},{
					moduleId:"header",
					ratio:"100%",
					position:[0,0],
				}],
				main:[{
					moduleId:"statsMobile",
					ratio:"100%",
					position:[0,0]
				}],
				  
				footer:[{
					moduleId:"navigationMobile",
					ratio:"100%",
					position:[0,0],

				}],
				side:[{
					moduleId:"sideNavigation",
					ratio:"100%",
					position:[0,0]
				},{
					moduleId:"challengeUserList",
					ratio:"100%",
					position:[0,0]
				}]
			}
		},
		
		user:{
			sections:{
				navigation:[{
					moduleId:"receiveChallenge",
					ratio:"100%",
					position:[0,0]
				},{
					moduleId:"header",
					ratio:"100%",
					position:[0,0],
				}],
				main:[{
					moduleId:"statsMobileUser",
					ratio:"100%",
					position:[0,0]
				}],
				  
				footer:[{
					moduleId:"navigationMobile",
					ratio:"100%",
					position:[0,0],

				}],
				side:[{
					moduleId:"sideNavigation",
					ratio:"100%",
					position:[0,0]
				},{
					moduleId:"challengeUserList",
					ratio:"100%",
					position:[0,0]
				}]
			}
		},
		settings:{
			sections:{
				navigation:[{
					moduleId:"receiveChallenge",
					ratio:"100%",
					position:[0,0]
				},{
					moduleId:"header",
					ratio:"100%",
					position:[0,0],
				}],
				main:[{
					moduleId:"settings",
					ratio:"100%",
					position:[0,0]
				}],
				  
				footer:[],
				side:[{
					moduleId:"sideNavigation",
					ratio:"100%",
					position:[0,0]
				},{
					moduleId:"challengeUserList",
					ratio:"100%",
					position:[0,0]
				}]
			}
		},
		logout:{
			sections:{
				navigation:[{
					moduleId:"receiveChallenge",
					ratio:"100%",
					position:[0,0]
				},{
					moduleId:"header",
					ratio:"100%",
					position:[0,0],
				}],
				main:[{
					moduleId:"logout",
					ratio:"100%",
					position:[0,0]
				}],
				  
				footer:[],
				side:[{
					moduleId:"sideNavigation",
					ratio:"100%",
					position:[0,0]
				},{
					moduleId:"challengeUserList",
					ratio:"100%",
					position:[0,0]
				}]
			}
		}
		
};
