/**
 * position:[row,column] 
 */
ZMO.modules_properties ={
		front:{
			sections:{
				navigation:[{
					moduleId:"receiveChallenge",
					ratio:"100%",
					position:[0,0],
					params:{}
				},{
					moduleId:"logout",
					ratio:"100%",
					position:[0,0],
				}],
				main:[{
					moduleId:"drawfeed",
					ratio:"100%",
					position:[0,0],
					params:{}
				}],
				  
				footer:[{
						moduleId:"navigationMobile",
						ratio:"100%",
						position:[0,0]
					}]
			}
		},
		duels:{
			sections:{
				navigation:[{
					moduleId:"receiveChallenge",
					ratio:"100%",
					position:[0,0]
				},{
					moduleId:"logout",
					ratio:"100%",
					position:[0,0],
				}],
				main:[{
					moduleId:"challenges",
					ratio:"100%",
					position:[0,0]
				}],
				  
				footer:[{
						moduleId:"navigationMobile",
						ratio:"100%",
						position:[0,0]
					}]
			}
		},
		dare:{
			sections:{
				navigation:[{
					moduleId:"receiveChallenge",
					ratio:"100%",
					position:[0,0]
				},{
					moduleId:"logout",
					ratio:"100%",
					position:[0,0],
				}],
				main:[{
					moduleId:"createChallenge",
					ratio:"100%",
					position:[0,0]
				}],
				  
				footer:[{
						moduleId:"navigationMobile",
						ratio:"100%",
						position:[0,0]
					}]
			}
		}
		
};
